### PR TITLE
Add some data to the website, document contribution steps

### PR DESCRIPTION
**Pull request by anshumanv**
Please review @scottydelta

### CODE REVIEW

**Comment by scottydelta** [comment]
May be add various URLs(pricing, privacy policies, website etc) in the JSON?

**Comment by anshumanv** [comment]
@scottydelta websites as in the link to the service? like `https://gmail.com` ?

**Comment by scottydelta** [comment]
Yes

**Comment by anshumanv** [comment]
Okay, on it, fixing that right away.

**Comment by anshumanv** [comment]
@scottydelta please see if this works for you. :smile:

**Comment by anshumanv** [comment]
> edit: Also it would be nice to segregate the JSONs based on the category(website, apps, android) and create app data folder structure accordingly.

I'm not sure if I get this correctly, can you give an example @scottydelta?

**Comment by anshumanv** [comment]
Ping @scottydelta

**Comment by scottydelta** [comment]
Since we are not just showing the data about third-party email providers but also listing other apps such as android, ios apps etc so it would make sense to categorize the JSONs in different folders.

something like:
```
    |-- src
    |-- data
        |-- apps
            |-- android_data.JSON
            |-- ios_data.JSON
        |-- websites
            |-- third_party_free.JSON
            |-- custom_domain.JSON
            |-- self_hosted.JSON
```
        
This is just a rough idea on organizing the data. Please feel free to edit the folder structure, rename the folders and files as you see them fit. thanks

**Comment by anshumanv** [comment]
@scottydelta I spent a lot of time researching, I couldn't find much data about the mobile apps, and the data I've provided is for service as a whole, segregated data as I researched through, I think any further updates/additions can be done by other contributors.
Should I submit the bounty?

**Comment by scottydelta** [comment]
Can you please make the following changes:

- Rename `third_party_free.JSON` to `transactional_emails.JSON`
- Add all the services which provide transactional emails, both free and paid (eg: [Mandrill](https://mandrill.com/) by MailChimp used to be paid/free but now it is only paid, please replace MailChimp with Mandrill since Mandrill is the transactional emails service and MailChimp is a marketing email service), add [MailGun](https://www.mailgun.com/) to the list. 
- We should remove Mad mimi as well, we dont want email marketing services to be in there and please remove any other such service.
- We should get android app data from play store, get top app names, ratings, downloads etc and then link to the playstore app, similarly for apple appstore too.
- Add self hosted email service data, refer to this [github repo](https://github.com/Kickball/awesome-selfhosted#email)

Please let me know what you think.  

thanks

**Comment by anshumanv** [comment]
@scottydelta updated.

**Comment by anshumanv** [comment]
@scottydelta ping

**Comment by scottydelta** [comment]
@anshumanv Hey, my apologies for a late response. Can you please update the readme/contribution guidelines aswell. 

@vikaskyadav Can you please check the JSON for the format as well as to see if it has all the data you would need to implement the [discussed features](https://github.com/emailsapp/emailsapp.github.io/issues/1#issuecomment-397839259). 

thanks

**Comment by anshumanv** [comment]
@scottydelta updating right away. :+1:

**Comment by anshumanv** [comment]
@scottydelta updated the contribution guidelines. :smile: 

> Should I submit the bounty?

Just saw that I've already submitted work long time ago. :sweat_smile:

**Comment by anshumanv** [comment]
Ping @scottydelta

**Comment by scottydelta** [comment]
@vikaskyadav Can you please check the JSON for the format as well as to see if it has all the data you would need to implement the [discussed features](https://github.com/emailsapp/emailsapp.github.io/issues/1#issuecomment-397839259) so that I can pay the bounty to the developer. thanks

**Comment by vikaskyadav** [comment]
looks good to me

**Comment by anshumanv** [comment]
@scottydelta :sparkles:

**Comment by scottydelta** [comment]
@anshumanv good work! thanks

**Pull request closed without merging**
